version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: 8IGoBXE2mkQFIU1RSwFFSr8AnDTI15oN
      POSTGRES_DB: drug_discovery_m3xe
    ports:
      - "5432:5432"
